# Generated by Django 5.1.7 on 2025-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Trousers', 'Trousers'), ('Jacket', 'Jacket'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories')], max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_company', models.CharField(max_length=255)),
                ('product_color', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=10, null=True)),
                ('product_material', models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Denim', 'Denim'), ('Leather', 'Leather'), ('Wool', 'Wool'), ('Silk', 'Silk'), ('Other', 'Other')], max_length=50)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('product_images', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
